//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceResidentClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceResidentClient.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string bio {
            get {
                return ResourceManager.GetString("bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Window.
        /// </summary>
        public static string borderlessWindow {
            get {
                return ResourceManager.GetString("borderlessWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each characteristic exponentially requires more points when it reaches a certain level.
        /// </summary>
        public static string characteristicTip1 {
            get {
                return ResourceManager.GetString("characteristicTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk.
        /// </summary>
        public static string clerk {
            get {
                return ResourceManager.GetString("clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering.
        /// </summary>
        public static string entering {
            get {
                return ResourceManager.GetString("entering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existentialism.
        /// </summary>
        public static string existentialism {
            get {
                return ResourceManager.GetString("existentialism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-knowledge, control of the body and emotions.
        /// </summary>
        public static string existentialismTT {
            get {
                return ResourceManager.GetString("existentialismTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flea market vendor.
        /// </summary>
        public static string fleaMarketVendor {
            get {
                return ResourceManager.GetString("fleaMarketVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string fullscreen {
            get {
                return ResourceManager.GetString("fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string human {
            get {
                return ResourceManager.GetString("human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinetics.
        /// </summary>
        public static string kinetics {
            get {
                return ResourceManager.GetString("kinetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body composition, agility and endurance.
        /// </summary>
        public static string kineticsTT {
            get {
                return ResourceManager.GetString("kineticsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguistics.
        /// </summary>
        public static string linguistics {
            get {
                return ResourceManager.GetString("linguistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily learns languages and memorizes text.
        /// </summary>
        public static string linguisticsTT {
            get {
                return ResourceManager.GetString("linguisticsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic.
        /// </summary>
        public static string logic {
            get {
                return ResourceManager.GetString("logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figures and calculations. Knowledge of formulas in the exact sciences.
        /// </summary>
        public static string logicTT {
            get {
                return ResourceManager.GetString("logicTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturalistics.
        /// </summary>
        public static string naturalistics {
            get {
                return ResourceManager.GetString("naturalistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge of flora and fauna.
        /// </summary>
        public static string naturalisticsTT {
            get {
                return ResourceManager.GetString("naturalisticsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string newGame {
            get {
                return ResourceManager.GetString("newGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no time data.
        /// </summary>
        public static string noTimeData {
            get {
                return ResourceManager.GetString("noTimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production worker.
        /// </summary>
        public static string productionWorker {
            get {
                return ResourceManager.GetString("productionWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string race {
            get {
                return ResourceManager.GetString("race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string relationships {
            get {
                return ResourceManager.GetString("relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent for communication, empathy for people, language skills.
        /// </summary>
        public static string relationshipsTT {
            get {
                return ResourceManager.GetString("relationshipsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Mode.
        /// </summary>
        public static string screenMode {
            get {
                return ResourceManager.GetString("screenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagination and creativity.
        /// </summary>
        public static string spaceTT {
            get {
                return ResourceManager.GetString("spaceTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string ua {
            get {
                return ResourceManager.GetString("ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployed.
        /// </summary>
        public static string unemployed {
            get {
                return ResourceManager.GetString("unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vun-flant.
        /// </summary>
        public static string vun_flant {
            get {
                return ResourceManager.GetString("vun-flant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vun-mis&apos;ak.
        /// </summary>
        public static string vun_mis_ak {
            get {
                return ResourceManager.GetString("vun-mis\'ak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vun-ti.
        /// </summary>
        public static string vun_ti {
            get {
                return ResourceManager.GetString("vun-ti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string windowed {
            get {
                return ResourceManager.GetString("windowed", resourceCulture);
            }
        }
    }
}
